server:
  port: 8084

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5435/authdb
    driver-class-name: org.h2.Driver
    username: authuser
    password: authpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:AjXVvMvzieSBc95uWqPOS8/1K2+K9GHiErd+dmwWQY8r+0n+YN7hIHCOXTliRK4x}
  expiration-ms: 86400000


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
