
services:
  plant-db:
    image: postgres:15
    container_name: plant-db
    environment:
      POSTGRES_DB: plantdb
      POSTGRES_USER: plantuser
      POSTGRES_PASSWORD: plantpass
    ports:
      - "5433:5432"
    networks:
      - plantnet

  watering-db:
    image: postgres:15
    container_name: watering-db
    environment:
      POSTGRES_DB: wateringdb
      POSTGRES_USER: wateringuser
      POSTGRES_PASSWORD: wateringpass
    ports:
      - "5434:5432"
    networks:
      - plantnet

  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    ports:
      - "5435:5432"
    networks:
      - plantnet

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - plantnet

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - plantnet

networks:
  plantnet:
    driver: bridge
