logging:
  level:
    root: INFO
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.generations: DEBUG

server:
  port: 8082

spring:
  application:
    name: watering-service

  datasource:
    url: jdbc:h2:mem:wateringdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



jwt:
  secret: ${JWT_SECRET:AjXVvMvzieSBc95uWqPOS8/1K2+K9GHiErd+dmwWQY8r+0n+YN7hIHCOXTliRK4x}