#logging:
#  level:
#    root: INFO
#    feign: DEBUG
#    org.springframework.cloud.openfeign: DEBUG
#    org.generations: DEBUG

server:
  port: 8082

spring:
  application:
    name: watering-service
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql


  datasource:
    url: jdbc:postgresql://localhost:5434/wateringdb
    username: wateringuser
    password: wateringpass


  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



jwt:
  secret: ${JWT_SECRET:AjXVvMvzieSBc95uWqPOS8/1K2+K9GHiErd+dmwWQY8r+0n+YN7hIHCOXTliRK4x}