#logging:
#  level:
#    root: DEBUG
#    org.springframework.cloud: DEBUG
#    feign: DEBUG
#    org.generations.plantservice.service: TRACE

server:
  port: 8081

spring:
  application:
    name: plant-service

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  datasource:
    url: jdbc:postgresql://localhost:5433/plantdb
    username: plantuser
    password: plantpass

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: plant-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


jwt:
  secret: ${JWT_SECRET:AjXVvMvzieSBc95uWqPOS8/1K2+K9GHiErd+dmwWQY8r+0n+YN7hIHCOXTliRK4x}
