name: CI - test, build & push images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  # 1. JOB MODIFICADO: Construye, instala Y sube el common-lib como Artefacto
  build-common-lib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Maven dependencies (optional, for speed)
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # ➡️ PASO CLAVE 1: Construir el JAR (usando verify para incluir tests)
      - name: Package common-lib artifact (Verify)
        working-directory: ./common-lib
        # Se usa 'verify' en lugar de 'package' para ejecutar cualquier test en la librería
        run: mvn -B -f pom.xml clean verify

      # ➡️ PASO CLAVE 2: Subir el JAR generado como un artefacto de GitHub.
      - name: Upload common-lib artifact
        uses: actions/upload-artifact@v4
        with:
          name: common-lib-jar
          path: ./common-lib/target/*.jar
          retention-days: 1

  # 2. JOB MODIFICADO: Descarga el Artefacto e instala la librería común
  test:
    needs: build-common-lib
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ "discovery-service", "gateway-service", "plant-service", "watering-service", "auth-service" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Maven repo (for other dependencies)
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # ➡️ PASO CLAVE 3: Descargar el JAR del job anterior.
      - name: Download common-lib artifact
        uses: actions/download-artifact@v4
        with:
          name: common-lib-jar
          path: common-lib-downloads/


      - name: Install common-lib into local Maven repo
        run: |
          JAR_PATH=$(find common-lib-downloads -name "common-lib-*.jar" | head -n 1)
          if [ -z "$JAR_PATH" ]; then
            echo "Error: common-lib JAR not found!"
            exit 1
          fi
          mvn install:install-file \
            -Dfile=$JAR_PATH \
            -DgroupId=org.generations \
            -DartifactId=common-lib \
            -Dversion=0.0.1-SNAPSHOT \
            -Dpackaging=jar \
            -B

      - name: Run tests for service ${{ matrix.service }}
        working-directory: ./${{ matrix.service }}
        run: mvn -B -f pom.xml clean verify

  # 3. JOB SIN CAMBIOS: Construye y empuja
  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ "discovery-service", "gateway-service", "plant-service", "watering-service", "auth-service" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU (for buildx)
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image for ${{ matrix.service }}
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max