name: CI - test, build & push images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  # 1. JOB MODIFICADO: Instala TODO localmente Y sube common-lib como Artefacto (Doble Seguridad)
  build-local-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # ➡️ PASO CLAVE 1: Instalar TODOS los artefactos locales (incluyendo el POM padre y common-lib)
      # Esto resuelve la dependencia 'plantas-micro:pom' y pone 'common-lib:jar' en el caché.
      - name: Install All Local SNAPSHOT dependencies
        run: mvn -B clean install -DskipTests=true

      # ➡️ PASO CLAVE 2: Subir el JAR de common-lib como un artefacto (Respaldo garantizado para el job 'test').
      # Aunque esté en el caché, lo subimos por si el job 'test' falla al restaurar.
      - name: Upload common-lib artifact for matrix jobs
        uses: actions/upload-artifact@v4
        with:
          name: common-lib-jar
          path: ./common-lib/target/*.jar
          retention-days: 1

  # 2. JOB MODIFICADO: Descarga el Artefacto e instala la librería común (Garantía de éxito)
  test:
    needs: build-local-dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ "discovery-service", "gateway-service", "plant-service", "watering-service", "auth-service" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # ➡️ PASO CLAVE 3: Restaurar el Caché (Debe contener plantas-micro:pom del job anterior)
      - name: Restore Maven repo cache (for parent POM and dependencies)
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # ➡️ PASO CLAVE 4: Descargar el JAR de common-lib (El respaldo explícito)
      - name: Download common-lib artifact
        uses: actions/download-artifact@v4
        with:
          name: common-lib-jar
          path: common-lib-downloads/

      # ➡️ PASO CLAVE 5: Instalar el JAR descargado forzosamente en el repositorio local.
      - name: Install common-lib into local Maven repo (Guaranteed fix)
        run: |
          # Identifica el JAR descargado.
          JAR_PATH=$(find common-lib-downloads -name "common-lib-*.jar" | head -n 1)
          if [ -z "$JAR_PATH" ]; then
            echo "Error: common-lib JAR not found in downloads!"
            exit 1
          fi
          # Instala el JAR manualmente.
          mvn install:install-file \
            -Dfile=$JAR_PATH \
            -DgroupId=org.generations \
            -DartifactId=common-lib \
            -Dversion=0.0.1-SNAPSHOT \
            -Dpackaging=jar \
            -B

      - name: Run tests for service ${{ matrix.service }}
        working-directory: ./${{ matrix.service }}
        # Ahora tanto el POM padre como common-lib están garantizados en el .m2
        run: mvn -B -f pom.xml clean verify

  # 3. JOB SIN CAMBIOS: Construye y empuja
  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ "discovery-service", "gateway-service", "plant-service", "watering-service", "auth-service" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU (for buildx)
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image for ${{ matrix.service }}
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max